export const sdgStockMap = {
  "ADANIGREEN": { name: "Adani Green Energy", tags: [7, 13] },
  "TATAPOWER": { name: "Tata Power", tags: [7, 13] },
  "SUNPHARMA": { name: "Sun Pharmaceutical", tags: [3] },
  "APOLLOHOSP": { name: "Apollo Hospitals", tags: [3] },
  "INFY": { name: "Infosys", tags: [9, 8] },
  "WIPRO": { name: "Wipro", tags: [9, 13] },
  "IRFC": { name: "Indian Railway Finance", tags: [9, 11] },
  "RELIANCE": { name: "Reliance Industries", tags: [7, 13] },
  "TCS": { name: "Tata Consultancy Services", tags: [9, 8] },
  "HDFCBANK": { name: "HDFC Bank", tags: [8, 10] },
  "ICICIBANK": { name: "ICICI Bank", tags: [8, 10] },
  "SBIN": { name: "State Bank of India", tags: [8, 10] },
  "LT": { name: "Larsen & Toubro", tags: [9, 11] },
  "BHARTIARTL": { name: "Bharti Airtel", tags: [9] },
  "HINDUNILVR": { name: "Hindustan Unilever", tags: [2, 3] },
  "ITC": { name: "ITC Limited", tags: [2, 12] },
  "AXISBANK": { name: "Axis Bank", tags: [8, 10] },
  "KOTAKBANK": { name: "Kotak Mahindra Bank", tags: [8, 10] },
  "MARUTI": { name: "Maruti Suzuki", tags: [8, 9, 11] },
  "TITAN": { name: "Titan Company", tags: [8, 12] },
  "ASIANPAINT": { name: "Asian Paints", tags: [9, 12] },
  "BAJFINANCE": { name: "Bajaj Finance", tags: [8, 10] },
  "ULTRACEMCO": { name: "UltraTech Cement", tags: [9, 11] },
  "NTPC": { name: "NTPC Limited", tags: [7, 13] },
  "POWERGRID": { name: "Power Grid", tags: [7, 9] },
  "TATASTEEL": { name: "Tata Steel", tags: [8, 9] },
  "HCLTECH": { name: "HCL Technologies", tags: [4, 9] },
  "ONGC": { name: "ONGC", tags: [7] },
  "TECHM": { name: "Tech Mahindra", tags: [8, 9] },
  "INDUSINDBK": { name: "IndusInd Bank", tags: [8, 10] }
};
